apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-team
  namespace: backend
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-team
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: backend-team
    namespace: backend
roleRef:
  kind: Role
  name: backend-team
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-team
  namespace: backend
secrets:
  - name: backend-team
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-team
  namespace: backend
  annotations:
    kubernetes.io/service-account.name: backend-team
type: kubernetes.io/service-account-token
