apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-web-server-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  