# permissions for end users to view postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-viewer-role
rules:
- apiGroups:
  - dabase.example.com
  resources:
  - postgresqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dabase.example.com
  resources:
  - postgresqls/status
  verbs:
  - get
